### ISSUE TITLE
Bug with trailing comma rule

### ISSUE THREAD

**Issue by KyllianV** [johnsoncodehk/vue-tsc#64]
Hello,

First of all, thanks for your work on this library.
I'm facing an issue with the `vue-tsc --noEmit` command. I have a component with 2 <script> tags like this :

```
<script lang="ts">
export default {
  inheritAttrs: false,
}
</script>

<script setup lang="ts">
 // some code...
</script>

<template>
 // some code...
</template>
```

As you can see I'm using the trailing-comma lint rule to add a comma at the end of the last line of my export default. But when I run `vue-tsc --noEmit`, I get the following error :

![image](https://user-images.githubusercontent.com/15817431/130320554-49923185-e197-41f2-8dad-450c3a6cdc5d.png)

If I remove the trailing comma, the command exits with no errors. Also, it's only in this particular case that I get the error, everywhere else in my code I have trailing commas and the `vue-tsc` works fine and don't throw any error.

I don't know if it's a problem with the double <script> tag or with the `export default` himself but there is an understanding problem with vue-tsc and the lint rule.

Thanks for your time, let me know if you need more details in this.

**Comment by johnsoncodehk** [comment]
This is a known issue and fixed in 0.27.4 (https://github.com/johnsoncodehk/volar/issues/383), please delete yarn.lock / package-lock.json and reinstall to update vscode-vue-languageservice.

**Comment by KyllianV** [comment]
It's not a problem with my editor or my volar extension, I'm running the `vue-tsc` from command line interface so updating vscode-vue-languageservice doesn't fix it.

**Comment by johnsoncodehk** [comment]
vscode-vue-languageservice not just a extension module, it is also a depend of vue-tsc: https://github.com/johnsoncodehk/vue-tsc/blob/master/package.json#L21

Please take a try.

**Comment by KyllianV** [comment]
Ok sorry it actually did the trick. I thought it wasn't working in the first place because I'm using pnpm and after removing pnpm-lock.yaml and reinstall, the dependency didn't upgrade. After running `pnpm up --latest vue-tsc` I finally get the latest version of vscode-vue-languageservice.

Thanks
